stages:
  load_data:
    cmd: python src/stage_1_load_save.py --config=config/config.yaml
    deps: 
      - src/stage_1_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - data/cat
      - data/dog
  prepare_base_model:
    cmd: python src/stage_2_prepare_basemodel.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_2_prepare_basemodel.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - config/config.yaml
      - params.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - CLASSES
    outs:
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/base_model/VGG16_base_model.h5
  

