stages:
  load_data:
    cmd: python src/stage_1_load_save.py --config=config/config.yaml
    deps: 
      - src/stage_1_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - data/cat
      - data/dog
  prepare_base_model:
    cmd: python src/stage_2_prepare_basemodel.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_2_prepare_basemodel.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - config/config.yaml
      - params.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - CLASSES
    outs:
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/base_model/VGG16_base_model.h5
  prepare_callbacks:
    cmd: python src/stage_3_prepare_callbacks.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_2_prepare_basemodel.py
      - src/utils/all_utils.py
      - src/utils/callbacks.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/callbacks/ccjeckpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
  train:
    cmd: python src/stage_4_train.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_4_train.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - src/utils/callbacks.py
      - src/utils/data_management.py
      - config/config.yaml
      - params.yaml
      - data/cat   # we can add -data also, instead of both
      - data/dog
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/callbacks/ccjeckpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
    params:
      - IMAGE_SIZE
      - CLASSES
      - AUGMENATATION
      - EPOCHS
    outs:
      - artifacts/model #since model name changes everytime, we are adding upt root folder level
      
  

